name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [x]
    paths:
      - '**'
      - '!**.md'
  push:
    branches: [x]
    paths:
      - '**'
      - '!**.md'
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight UTC

jobs:
  build-macos-env:
    name: Build/cache macOS Nix env
    strategy:
      matrix:
        os: [macos-11, macos-13-arm64]
        include:
          - os: macos-11
            flake: ci-x86
          - os: macos-13-arm64
            flake: ci-arm
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      # TODO: Add Cachix support
      # - name: Setup Cachix
      #   uses: cachix/cachix-action@v12
      #   with:
      #     name: matt
      #     signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}

      - name: If scheduled, update inputs
        if: ${{ github.event_name == 'schedule' && success() }}
        run: |
          nix flake update

      - name: Build
        run: |
          nix build .#darwinConfigurations.${{ matrix.flake }}.system
          ./result/sw/bin/darwin-rebuild switch --flake .#${{ matrix.flake }}

      - name: If scheduled, push commit with updated inputs
        if: ${{ github.event_name == 'schedule' && success() }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git aa
          git cm "Update inputs"
          git push
