name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
    paths:
      - '**'
      - '!**.md'
      - '!.github/workflows/deps.yml'
      - '!.github/workflows/pr.yml'

jobs:
  ci:
    name: CI
    strategy:
      matrix:
        flake: [ci-intel, ci-arm]
        include:
          - flake: ci-intel
            runner: macos-11
          - flake: ci-arm
            runner: macos-13-xlarge # This is the only runner with arm64, and it $$$
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Setup Cachix
        uses: cachix/cachix-action@v12
        with:
          name: preucil
          authToken: ${{ secrets.CACHIX_TOKEN }}

      - name: Build
        run: |
          nix build .#darwinConfigurations.${{ matrix.flake }}.system

      - name: Switch
        run: |
          sudo mv /etc/nix/nix.conf /etc/nix/nix.conf.bak
          ./result/sw/bin/darwin-rebuild switch --flake .#${{ matrix.flake }}
