name: Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Every night at midnight UTC

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: macos-14

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: preucil
          authToken: ${{ secrets.CACHIX_TOKEN }}

      - name: Update Flake Inputs
        run: |
          nix flake update

      - name: Update VSCode Extensions
        working-directory: ./config/vscode/extensions
        run: |
          ./update.sh

      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update Dependencies
          title: Update Dependencies
          labels: allow-auto-merge
          branch: update-dependencies
