name: PR

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable-auto-merge-if-needed:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/enable-pull-request-automerge@v3
        if: contains(github.event.pull_request.labels.*.name, 'allow-auto-merge')
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: rebase
